# -*- coding: utf-8 -*-
# @Author: jsgounot
# @Date:   2022-03-28 19:32:34
# @Last Modified by:   jsgounot
# @Last Modified time: 2022-03-29 11:32:42

from Bio import SeqIO

def main(fnames, outfile):
    idx = 1
    with open(outfile, 'w') as f:
        f.write('#Auto generated by snakemake pipeline\n')
        for sample, fname in fnames.items():
            fdata = SeqIO.parse(fname, 'fasta')
            for ridx, record in enumerate(fdata):
                line = f'chr - {record.id} {sample}_{ridx} 0 {len(record.seq)} chr{idx} \n'
                f.write(line)
                idx += 1

fnames = snakemake.params[0]
outfile = snakemake.output[0]
main(fnames, outfile)
